name: Build documentation

on:
    push:
        branches: [ "main" ]

jobs:
    build-and-deploy:
        concurrency: ci-${{ github.ref }}
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout 🛎️
                uses: actions/checkout@v4

            -   name: Install and Build 🔧
                run: |
                    npm ci
                    npm run docs:build

            -   name: Deploy 🚀
                uses: JamesIves/github-pages-deploy-action@v4
                with:
                    folder: ./docs
                    token: ${{ secrets.TOKEN }}
