name: Build documentation

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Build Docusaurus website
        run: |
          cd site
          npm install 
          npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.NPM_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site/build
