name: Test

on: push

permissions:
  contents: read

jobs:
  npm-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-install-${{ hashFiles('package-lock.json', 'package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-install-

      - name: npm install
        run: |
          npm install

  lint:
    runs-on: ubuntu-latest
    needs:
      - npm-install
    steps:
      - name: npm cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-install-${{ hashFiles('package-lock.json', 'package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-install-

      - uses: actions/checkout@v3
      - name: npm lint
        run: |
          npm run lint

  test:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: npm cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-install-${{ hashFiles('package-lock.json', 'package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-install-

      - uses: actions/checkout@v3
      - name: test
        run: |
          npm run test
